// <auto-generated />
using System;
using AndonApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AndonApp.Migrations
{
    [DbContext(typeof(AndonDbContext))]
    partial class AndonDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AndonApp.Data.Models.AdminUser", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd()
                    .HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("PasswordHash").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<string>("Username").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.HasKey("Id");
                b.ToTable("AdminUsers");
            });

            modelBuilder.Entity("AndonApp.Data.Models.AndonCode", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("Code").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<string>("Description").HasMaxLength(500).HasColumnType("nvarchar(500)");
                b.Property<bool>("IsActive").HasColumnType("bit");
                b.Property<string>("Name").HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.HasKey("Id");
                b.ToTable("AndonCodes");
            });

            modelBuilder.Entity("AndonApp.Data.Models.AndonCodeRecipient", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<int>("AndonCodeId").HasColumnType("int");
                b.Property<string>("Email").IsRequired().HasMaxLength(254).HasColumnType("nvarchar(254)");
                b.HasKey("Id");
                b.HasIndex("AndonCodeId", "Email").IsUnique();
                b.ToTable("AndonCodeRecipients");
            });

            modelBuilder.Entity("AndonApp.Data.Models.Incident", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<int>("AndonCodeId").HasColumnType("int");
                b.Property<string>("AdditionalInfo").HasMaxLength(1000).HasColumnType("nvarchar(1000)");
                b.Property<DateTime?>("ClosedAt").HasColumnType("datetime2");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<int>("ProductionLineId").HasColumnType("int");
                b.Property<string>("Severity").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
                b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
                b.HasKey("Id");
                b.HasIndex("AndonCodeId");
                b.HasIndex("ProductionLineId", "CreatedAt");
                b.HasIndex("ProductionLineId", "Status");
                b.ToTable("Incidents");
            });

            modelBuilder.Entity("AndonApp.Data.Models.ProductionLine", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("AccessToken").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<bool>("IsActive").HasColumnType("bit");
                b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<string>("Slug").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.HasKey("Id");
                b.HasIndex("Slug").IsUnique();
                b.ToTable("ProductionLines");
            });

            modelBuilder.Entity("AndonApp.Data.Models.AndonCodeRecipient", b =>
            {
                b.HasOne("AndonApp.Data.Models.AndonCode", "AndonCode")
                    .WithMany("Recipients")
                    .HasForeignKey("AndonCodeId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("AndonCode");
            });

            modelBuilder.Entity("AndonApp.Data.Models.Incident", b =>
            {
                b.HasOne("AndonApp.Data.Models.AndonCode", "AndonCode")
                    .WithMany("Incidents")
                    .HasForeignKey("AndonCodeId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
                b.HasOne("AndonApp.Data.Models.ProductionLine", "ProductionLine")
                    .WithMany("Incidents")
                    .HasForeignKey("ProductionLineId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
                b.Navigation("AndonCode");
                b.Navigation("ProductionLine");
            });

            modelBuilder.Entity("AndonApp.Data.Models.AndonCode", b =>
            {
                b.Navigation("Incidents");
                b.Navigation("Recipients");
            });

            modelBuilder.Entity("AndonApp.Data.Models.ProductionLine", b =>
            {
                b.Navigation("Incidents");
            });
#pragma warning restore 612, 618
        }
    }
}
